title: My Portfolio
description: A portfolio of projects and things I have made.
url: "https://metzinaround.github.io"
baseurl: "/my-first-portfolio" 

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
